drop table if exists member CASCADE;

create table member
(
    id varchar(15),
    password varchar(15),
    nickname     varchar(255),
);

drop table if exists account CASCADE;

create table account
(
    division_id bigint generated by default as identity,
    username      varchar(255),
    item     varchar(255),
    type    varchar(255),
    price    bigint,
    date     DATETIME not null default CURRENT_TIMESTAMP
)

drop table if exists calculator CASCADE;

create table calculator
(
    division_id bigint generated by default as identity,
    username    varchar(255),
    export_sum bigint,
    import_sum bigint,
    date     DATETIME not null default CURRENT_TIMESTAMP
)
