drop table if exists member CASCADE;

create table member
(
    id varchar(255),
    password varchar(255),
    nickname     varchar(255)
);

drop table if exists account CASCADE;

create table account
(
    division_id bigint generated by default as identity,
    username      varchar(255),
    item     varchar(255),
    type    varchar(255),
    price    bigint,
    date     DATETIME not null default CURRENT_TIMESTAMP
)

drop table if exists calculator CASCADE;

create table calculator
(
    division_id bigint generated by default as identity,
    username    varchar(255),
    export_sum bigint,
    import_sum bigint,
    date     DATETIME not null default CURRENT_TIMESTAMP
)

drop table if exists board CASCADE;

create table board
(
    id       bigint generated by default as identity,
    nickname     varchar(255),
    title    varchar(255),
    content  varchar(1000),
    date     DATETIME not null default CURRENT_TIMESTAMP,
    primary key (id)
);